name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      
    - name: Restore
      working-directory: /src
      run: dotnet restore

    - name: Build
      working-directory: /src
      run: dotnet build /warnaserror
